/*
 * Generated by PEG.js 0.10.0.
 *
 * http://pegjs.org/
 */

"use strict";

function peg$subclass(child, parent) {
  function ctor() { this.constructor = child; }
  ctor.prototype = parent.prototype;
  child.prototype = new ctor();
}

function peg$SyntaxError(message, expected, found, location) {
  this.message  = message;
  this.expected = expected;
  this.found    = found;
  this.location = location;
  this.name     = "SyntaxError";

  if (typeof Error.captureStackTrace === "function") {
    Error.captureStackTrace(this, peg$SyntaxError);
  }
}

peg$subclass(peg$SyntaxError, Error);

peg$SyntaxError.buildMessage = function(expected, found) {
  var DESCRIBE_EXPECTATION_FNS = {
        literal: function(expectation) {
          return "\"" + literalEscape(expectation.text) + "\"";
        },

        "class": function(expectation) {
          var escapedParts = "",
              i;

          for (i = 0; i < expectation.parts.length; i++) {
            escapedParts += expectation.parts[i] instanceof Array
              ? classEscape(expectation.parts[i][0]) + "-" + classEscape(expectation.parts[i][1])
              : classEscape(expectation.parts[i]);
          }

          return "[" + (expectation.inverted ? "^" : "") + escapedParts + "]";
        },

        any: function(expectation) {
          return "any character";
        },

        end: function(expectation) {
          return "end of input";
        },

        other: function(expectation) {
          return expectation.description;
        }
      };

  function hex(ch) {
    return ch.charCodeAt(0).toString(16).toUpperCase();
  }

  function literalEscape(s) {
    return s
      .replace(/\\/g, '\\\\')
      .replace(/"/g,  '\\"')
      .replace(/\0/g, '\\0')
      .replace(/\t/g, '\\t')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/[\x00-\x0F]/g,          function(ch) { return '\\x0' + hex(ch); })
      .replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) { return '\\x'  + hex(ch); });
  }

  function classEscape(s) {
    return s
      .replace(/\\/g, '\\\\')
      .replace(/\]/g, '\\]')
      .replace(/\^/g, '\\^')
      .replace(/-/g,  '\\-')
      .replace(/\0/g, '\\0')
      .replace(/\t/g, '\\t')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/[\x00-\x0F]/g,          function(ch) { return '\\x0' + hex(ch); })
      .replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) { return '\\x'  + hex(ch); });
  }

  function describeExpectation(expectation) {
    return DESCRIBE_EXPECTATION_FNS[expectation.type](expectation);
  }

  function describeExpected(expected) {
    var descriptions = new Array(expected.length),
        i, j;

    for (i = 0; i < expected.length; i++) {
      descriptions[i] = describeExpectation(expected[i]);
    }

    descriptions.sort();

    if (descriptions.length > 0) {
      for (i = 1, j = 1; i < descriptions.length; i++) {
        if (descriptions[i - 1] !== descriptions[i]) {
          descriptions[j] = descriptions[i];
          j++;
        }
      }
      descriptions.length = j;
    }

    switch (descriptions.length) {
      case 1:
        return descriptions[0];

      case 2:
        return descriptions[0] + " or " + descriptions[1];

      default:
        return descriptions.slice(0, -1).join(", ")
          + ", or "
          + descriptions[descriptions.length - 1];
    }
  }

  function describeFound(found) {
    return found ? "\"" + literalEscape(found) + "\"" : "end of input";
  }

  return "Expected " + describeExpected(expected) + " but " + describeFound(found) + " found.";
};

function peg$parse(input, options) {
  options = options !== void 0 ? options : {};

  var peg$FAILED = {},

      peg$startRuleIndices = { Grammar: 0 },
      peg$startRuleIndex   = 0,

      peg$consts = [
        function(spacing, definitions, endoffile) {
            return {
              type: 'Grammar',
              spacing: spacing,
              definitions: definitions,
              endoffile: endoffile,
            };
          },
        function(identifier, leftarrow, expression) {
            return {
              type: 'Definition',
              identifier: identifier,
              leftarrow: leftarrow,
              expression: expression
            };
          },
        function(first, slash, sequence) {
            return {
              slash: slash,
              sequence: sequence
            };
          },
        function(first, alternates) {
            return {
              type: 'Expression',
              sequence: first,
              alternates: alternates
            };
          },
        function(prefixes) {
            return {
              type: 'Sequence',
              prefixes: prefixes
            };
          },
        function(prefix, suffix) {
            if (prefix) {
              return {
                type: 'Prefix',
                prefix: prefix,
                suffix: suffix
              };
            }
            return {
              type: 'Prefix',
              suffix: suffix
            };
          },
        function(primary, suffix) {
            if (suffix) {
              return {
                type: 'Suffix',
                primary: primary,
                suffix: suffix
              };
            }
            return {
              type: 'Suffix',
              primary: primary
            };
          },
        function(identifier) {
            return {
              type: 'Primary',
              identifier: identifier
            };
          },
        function(open, expression, close) {
            return {
              type: 'Primary',
              open: open,
              expression: expression,
              close: close
            };
          },
        function(literal) {
            return {
              type: 'Primary',
              literal: literal
            };
          },
        function(cls) {
            return {
              type: 'Primary',
              class: cls
            };
          },
        function(dot) {
            return {
              type: 'Primary',
              dot: dot
            };
          },
        function(identstart, identconts, spacing) {
            return {
              type: 'Identifier',
              identstart: identstart,
              identconts: identconts,
              spacing: spacing
            };
          },
        /^[a-z_]/i,
        peg$classExpectation([["a", "z"], "_"], false, true),
        function() { return makeText(); },
        function(text) {
            return {
              type: 'IdentStart',
              text: text
            };
          },
        function(identstart) {
            return {
              type: 'IdentCont',
              identstart: identstart
            };
          },
        /^[0-9]/,
        peg$classExpectation([["0", "9"]], false, false),
        function() {
            return {
              type: 'IdentCont',
              text: makeText()
            };
          },
        /^[']/,
        peg$classExpectation(["'"], false, false),
        function(open, char) { return char; },
        function(open, chars) { return makeText(); },
        /^["]/,
        peg$classExpectation(["\""], false, false),
        function(open, chars, close, spacing) {
            return {
              type: 'Literal',
              open: open,
              chars: chars,
              close: close,
              spacing: spacing
            };
          },
        "[",
        peg$literalExpectation("[", false),
        "]",
        peg$literalExpectation("]", false),
        function(open, range) { return range; },
        function(open, ranges) { return makeText(); },
        function(open, ranges, close, spacing) {
            return {
              type: 'Class',
              open: open,
              ranges: ranges,
              close: close,
              spacing: spacing
            };
          },
        "-",
        peg$literalExpectation("-", false),
        function(start) { return makeText(); },
        function(start, text, end) {
            return {
              type: 'Range',
              start: start,
              text: text,
              end: end
            };
          },
        function(start) {
            return {
              type: 'Range',
              start: start
            };
          },
        "\\",
        peg$literalExpectation("\\", false),
        /^[nrt'"[\]\\]/,
        peg$classExpectation(["n", "r", "t", "'", "\"", "[", "]", "\\"], false, false),
        /^[0-2]/,
        peg$classExpectation([["0", "2"]], false, false),
        /^[0-7]/,
        peg$classExpectation([["0", "7"]], false, false),
        peg$anyExpectation(),
        function() {
            return {
              type: 'Char',
              text: makeText()
            };
          },
        "<-",
        peg$literalExpectation("<-", false),
        function(text, spacing) {
            return {
              type: 'LEFTARROW',
              text: text,
              spacing: spacing
            };
          },
        "/",
        peg$literalExpectation("/", false),
        function(text, spacing) {
            return {
              type: 'SLASH',
              text: text,
              spacing: spacing
            };
          },
        "&",
        peg$literalExpectation("&", false),
        function(text, spacing) {
            return {
              type: 'AND',
              text: text,
              spacing: spacing
            };
          },
        "!",
        peg$literalExpectation("!", false),
        function(text, spacing) {
            return {
              type: 'NOT',
              text: text,
              spacing: spacing
            };
          },
        "?",
        peg$literalExpectation("?", false),
        function(text, spacing) {
            return {
              type: 'QUESTION',
              text: text,
              spacing: spacing
            };
          },
        "*",
        peg$literalExpectation("*", false),
        function(text, spacing) {
            return {
              type: 'STAR',
              text: text,
              spacing: spacing
            };
          },
        "+",
        peg$literalExpectation("+", false),
        function(text, spacing) {
            return {
              type: 'PLUS',
              text: text,
              spacing: spacing
            };
          },
        "(",
        peg$literalExpectation("(", false),
        function(text, spacing) {
            return {
              type: 'OPEN',
              text: text,
              spacing: spacing
            };
          },
        ")",
        peg$literalExpectation(")", false),
        function(text, spacing) {
            return {
              type: 'CLOSE',
              text: text,
              spacing: spacing
            };
          },
        ".",
        peg$literalExpectation(".", false),
        function(text, spacing) {
            return {
              type: 'DOT',
              text: text,
              spacing: spacing
            };
          },
        function(spaces) {
            return {
              type: 'Spacing',
              spaces: spaces
            };
          },
        "#",
        peg$literalExpectation("#", false),
        function(start, content, endofline) {
            return {
              type: 'Comment',
              start: start,
              content: content,
              endofline: endofline
            };
          },
        " ",
        peg$literalExpectation(" ", false),
        "\t",
        peg$literalExpectation("\t", false),
        function() {
            return {
              type: 'Space',
              text: makeText()
            };
          },
        function(endofline) {
            return {
              type: 'Space',
              endofline: endofline
            };
          },
        "\r\n",
        peg$literalExpectation("\r\n", false),
        "\n",
        peg$literalExpectation("\n", false),
        "\r",
        peg$literalExpectation("\r", false),
        function() {
            return {
              type: 'EndOfLine',
              endofline: makeText()
            };
          },
        function() {
            return {
              type: 'EndOfFile',
            };
          }
      ],

      peg$bytecode = [
        peg$decode("%;8/I#$;!/&#0#*;!&&&#/3$;</*$8#: ##\"! )(#'#(\"'#&'#"),
        peg$decode("%;'/<#;./3$;\"/*$8#:!##\"! )(#'#(\"'#&'#"),
        peg$decode("%;#/m#$%;//3#;#/*$8\":\"\"#$! )(\"'#&'#0=*%;//3#;#/*$8\":\"\"#$! )(\"'#&'#&/)$8\":#\"\"! )(\"'#&'#"),
        peg$decode("%$;$0#*;$&/' 8!:$!! )"),
        peg$decode("%;0.# &;1.\" &\"/2#;%/)$8\":%\"\"! )(\"'#&'#"),
        peg$decode("%;&/C#;2.) &;3.# &;4.\" &\"/)$8\":&\"\"! )(\"'#&'#"),
        peg$decode("%;'/=#%<;.=.##&&!&'#/($8\":'\"!!)(\"'#&'#.| &%;5/<#;\"/3$;6/*$8#:(##\"! )(#'#(\"'#&'#.S &%;*/' 8!:)!! ).A &%;+/' 8!:*!! )./ &%;7/' 8!:+!! )"),
        peg$decode("%;(/C#$;)0#*;)&/3$;8/*$8#:,##\"! )(#'#(\"'#&'#"),
        peg$decode("%%4-\"\"5!7./& 8!:/! )/' 8!:0!! )"),
        peg$decode("%;(/' 8!:1!! ).4 &%42\"\"5!73/& 8!:4! )"),
        peg$decode("%%45\"\"5!76/& 8!:/! )/\xAE#$%%<45\"\"5!76=.##&&!&'#/2#;-/)$8\":7\"\"$ )(\"'#&'#0N*%%<45\"\"5!76=.##&&!&'#/2#;-/)$8\":7\"\"$ )(\"'#&'#&/H$%45\"\"5!76/( 8!:8!\"#\")/,$;8/#$+$)($'#(#'#(\"'#&'#.\xD1 &%%49\"\"5!7:/& 8!:/! )/\xB6#$%%<49\"\"5!7:=.##&&!&'#/2#;-/)$8\":7\"\"$ )(\"'#&'#0N*%%<49\"\"5!7:=.##&&!&'#/2#;-/)$8\":7\"\"$ )(\"'#&'#&/P$%49\"\"5!7:/( 8!:8!\"#\")/4$;8/+$8$:;$$#\"! )($'#(#'#(\"'#&'#"),
        peg$decode("%%2<\"\"6<7=/& 8!:/! )/\xB6#$%%<2>\"\"6>7?=.##&&!&'#/2#;,/)$8\":@\"\"$ )(\"'#&'#0N*%%<2>\"\"6>7?=.##&&!&'#/2#;,/)$8\":@\"\"$ )(\"'#&'#&/P$%2>\"\"6>7?/( 8!:A!\"#\")/4$;8/+$8$:B$$#\"! )($'#(#'#(\"'#&'#"),
        peg$decode("%;-/N#%2C\"\"6C7D/' 8!:E!!\")/3$;-/*$8#:F##\"! )(#'#(\"'#&'#./ &%;-/' 8!:G!! )"),
        peg$decode("%2H\"\"6H7I/2#4J\"\"5!7K/#$+\")(\"'#&'#.\xCD &%2H\"\"6H7I/P#4L\"\"5!7M/A$4N\"\"5!7O/2$4N\"\"5!7O/#$+$)($'#(#'#(\"'#&'#.\x8A &%2H\"\"6H7I/F#4N\"\"5!7O/7$4N\"\"5!7O.\" &\"/#$+#)(#'#(\"'#&'#.Q &%%<2H\"\"6H7I=.##&&!&'#/5#1\"\"5!7P/'$8\":Q\" )(\"'#&'#"),
        peg$decode("%%2R\"\"6R7S/& 8!:/! )/2#;8/)$8\":T\"\"! )(\"'#&'#"),
        peg$decode("%%2U\"\"6U7V/& 8!:/! )/2#;8/)$8\":W\"\"! )(\"'#&'#"),
        peg$decode("%%2X\"\"6X7Y/& 8!:/! )/2#;8/)$8\":Z\"\"! )(\"'#&'#"),
        peg$decode("%%2[\"\"6[7\\/& 8!:/! )/2#;8/)$8\":]\"\"! )(\"'#&'#"),
        peg$decode("%%2^\"\"6^7_/& 8!:/! )/2#;8/)$8\":`\"\"! )(\"'#&'#"),
        peg$decode("%%2a\"\"6a7b/& 8!:/! )/2#;8/)$8\":c\"\"! )(\"'#&'#"),
        peg$decode("%%2d\"\"6d7e/& 8!:/! )/2#;8/)$8\":f\"\"! )(\"'#&'#"),
        peg$decode("%%2g\"\"6g7h/& 8!:/! )/2#;8/)$8\":i\"\"! )(\"'#&'#"),
        peg$decode("%%2j\"\"6j7k/& 8!:/! )/2#;8/)$8\":l\"\"! )(\"'#&'#"),
        peg$decode("%%2m\"\"6m7n/& 8!:/! )/2#;8/)$8\":o\"\"! )(\"'#&'#"),
        peg$decode("%$;:.# &;90)*;:.# &;9&/' 8!:p!! )"),
        peg$decode("%%2q\"\"6q7r/& 8!:/! )/\x95#$%%<;;=.##&&!&'#/6#1\"\"5!7P/($8\":E\"!$)(\"'#&'#0L*%%<;;=.##&&!&'#/6#1\"\"5!7P/($8\":E\"!$)(\"'#&'#&/3$;;/*$8#:s##\"! )(#'#(\"'#&'#"),
        peg$decode("%2t\"\"6t7u.) &2v\"\"6v7w/& 8!:x! )./ &%;;/' 8!:y!! )"),
        peg$decode("%2z\"\"6z7{.5 &2|\"\"6|7}.) &2~\"\"6~7\x7F/& 8!:\x80! )"),
        peg$decode("%%<1\"\"5!7P=.##&&!&'#/& 8!:\x81! )")
      ],

      peg$currPos          = 0,
      peg$savedPos         = 0,
      peg$posDetailsCache  = [{ line: 1, column: 1 }],
      peg$maxFailPos       = 0,
      peg$maxFailExpected  = [],
      peg$silentFails      = 0,

      peg$resultsCache = {},

      peg$result;

  if ("startRule" in options) {
    if (!(options.startRule in peg$startRuleIndices)) {
      throw new Error("Can't start parsing from rule \"" + options.startRule + "\".");
    }

    peg$startRuleIndex = peg$startRuleIndices[options.startRule];
  }

  function text() {
    return input.substring(peg$savedPos, peg$currPos);
  }

  function location() {
    return peg$computeLocation(peg$savedPos, peg$currPos);
  }

  function expected(description, location) {
    location = location !== void 0 ? location : peg$computeLocation(peg$savedPos, peg$currPos)

    throw peg$buildStructuredError(
      [peg$otherExpectation(description)],
      input.substring(peg$savedPos, peg$currPos),
      location
    );
  }

  function error(message, location) {
    location = location !== void 0 ? location : peg$computeLocation(peg$savedPos, peg$currPos)

    throw peg$buildSimpleError(message, location);
  }

  function peg$literalExpectation(text, ignoreCase) {
    return { type: "literal", text: text, ignoreCase: ignoreCase };
  }

  function peg$classExpectation(parts, inverted, ignoreCase) {
    return { type: "class", parts: parts, inverted: inverted, ignoreCase: ignoreCase };
  }

  function peg$anyExpectation() {
    return { type: "any" };
  }

  function peg$endExpectation() {
    return { type: "end" };
  }

  function peg$otherExpectation(description) {
    return { type: "other", description: description };
  }

  function peg$computePosDetails(pos) {
    var details = peg$posDetailsCache[pos], p;

    if (details) {
      return details;
    } else {
      p = pos - 1;
      while (!peg$posDetailsCache[p]) {
        p--;
      }

      details = peg$posDetailsCache[p];
      details = {
        line:   details.line,
        column: details.column
      };

      while (p < pos) {
        if (input.charCodeAt(p) === 10) {
          details.line++;
          details.column = 1;
        } else {
          details.column++;
        }

        p++;
      }

      peg$posDetailsCache[pos] = details;
      return details;
    }
  }

  function peg$computeLocation(startPos, endPos) {
    var startPosDetails = peg$computePosDetails(startPos),
        endPosDetails   = peg$computePosDetails(endPos);

    return {
      start: {
        offset: startPos,
        line:   startPosDetails.line,
        column: startPosDetails.column
      },
      end: {
        offset: endPos,
        line:   endPosDetails.line,
        column: endPosDetails.column
      }
    };
  }

  function peg$fail(expected) {
    if (peg$currPos < peg$maxFailPos) { return; }

    if (peg$currPos > peg$maxFailPos) {
      peg$maxFailPos = peg$currPos;
      peg$maxFailExpected = [];
    }

    peg$maxFailExpected.push(expected);
  }

  function peg$buildSimpleError(message, location) {
    return new peg$SyntaxError(message, null, null, location);
  }

  function peg$buildStructuredError(expected, found, location) {
    return new peg$SyntaxError(
      peg$SyntaxError.buildMessage(expected, found),
      expected,
      found,
      location
    );
  }

  function peg$decode(s) {
    var bc = new Array(s.length), i;

    for (i = 0; i < s.length; i++) {
      bc[i] = s.charCodeAt(i) - 32;
    }

    return bc;
  }

  function peg$parseRule(index) {
    var bc    = peg$bytecode[index],
        ip    = 0,
        ips   = [],
        end   = bc.length,
        ends  = [],
        stack = [],
        params, i;

    var key    = peg$currPos * 29 + index,
        cached = peg$resultsCache[key];

    if (cached) {
      peg$currPos = cached.nextPos;

      return cached.result;
    }

    while (true) {
      while (ip < end) {
        switch (bc[ip]) {
          case 0:
            stack.push(peg$consts[bc[ip + 1]]);
            ip += 2;
            break;

          case 1:
            stack.push(void 0);
            ip++;
            break;

          case 2:
            stack.push(null);
            ip++;
            break;

          case 3:
            stack.push(peg$FAILED);
            ip++;
            break;

          case 4:
            stack.push([]);
            ip++;
            break;

          case 5:
            stack.push(peg$currPos);
            ip++;
            break;

          case 6:
            stack.pop();
            ip++;
            break;

          case 7:
            peg$currPos = stack.pop();
            ip++;
            break;

          case 8:
            stack.length -= bc[ip + 1];
            ip += 2;
            break;

          case 9:
            stack.splice(-2, 1);
            ip++;
            break;

          case 10:
            stack[stack.length - 2].push(stack.pop());
            ip++;
            break;

          case 11:
            stack.push(stack.splice(stack.length - bc[ip + 1], bc[ip + 1]));
            ip += 2;
            break;

          case 12:
            stack.push(input.substring(stack.pop(), peg$currPos));
            ip++;
            break;

          case 13:
            ends.push(end);
            ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

            if (stack[stack.length - 1]) {
              end = ip + 3 + bc[ip + 1];
              ip += 3;
            } else {
              end = ip + 3 + bc[ip + 1] + bc[ip + 2];
              ip += 3 + bc[ip + 1];
            }

            break;

          case 14:
            ends.push(end);
            ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

            if (stack[stack.length - 1] === peg$FAILED) {
              end = ip + 3 + bc[ip + 1];
              ip += 3;
            } else {
              end = ip + 3 + bc[ip + 1] + bc[ip + 2];
              ip += 3 + bc[ip + 1];
            }

            break;

          case 15:
            ends.push(end);
            ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

            if (stack[stack.length - 1] !== peg$FAILED) {
              end = ip + 3 + bc[ip + 1];
              ip += 3;
            } else {
              end = ip + 3 + bc[ip + 1] + bc[ip + 2];
              ip += 3 + bc[ip + 1];
            }

            break;

          case 16:
            if (stack[stack.length - 1] !== peg$FAILED) {
              ends.push(end);
              ips.push(ip);

              end = ip + 2 + bc[ip + 1];
              ip += 2;
            } else {
              ip += 2 + bc[ip + 1];
            }

            break;

          case 17:
            ends.push(end);
            ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

            if (input.length > peg$currPos) {
              end = ip + 3 + bc[ip + 1];
              ip += 3;
            } else {
              end = ip + 3 + bc[ip + 1] + bc[ip + 2];
              ip += 3 + bc[ip + 1];
            }

            break;

          case 18:
            ends.push(end);
            ips.push(ip + 4 + bc[ip + 2] + bc[ip + 3]);

            if (input.substr(peg$currPos, peg$consts[bc[ip + 1]].length) === peg$consts[bc[ip + 1]]) {
              end = ip + 4 + bc[ip + 2];
              ip += 4;
            } else {
              end = ip + 4 + bc[ip + 2] + bc[ip + 3];
              ip += 4 + bc[ip + 2];
            }

            break;

          case 19:
            ends.push(end);
            ips.push(ip + 4 + bc[ip + 2] + bc[ip + 3]);

            if (input.substr(peg$currPos, peg$consts[bc[ip + 1]].length).toLowerCase() === peg$consts[bc[ip + 1]]) {
              end = ip + 4 + bc[ip + 2];
              ip += 4;
            } else {
              end = ip + 4 + bc[ip + 2] + bc[ip + 3];
              ip += 4 + bc[ip + 2];
            }

            break;

          case 20:
            ends.push(end);
            ips.push(ip + 4 + bc[ip + 2] + bc[ip + 3]);

            if (peg$consts[bc[ip + 1]].test(input.charAt(peg$currPos))) {
              end = ip + 4 + bc[ip + 2];
              ip += 4;
            } else {
              end = ip + 4 + bc[ip + 2] + bc[ip + 3];
              ip += 4 + bc[ip + 2];
            }

            break;

          case 21:
            stack.push(input.substr(peg$currPos, bc[ip + 1]));
            peg$currPos += bc[ip + 1];
            ip += 2;
            break;

          case 22:
            stack.push(peg$consts[bc[ip + 1]]);
            peg$currPos += peg$consts[bc[ip + 1]].length;
            ip += 2;
            break;

          case 23:
            stack.push(peg$FAILED);
            if (peg$silentFails === 0) {
              peg$fail(peg$consts[bc[ip + 1]]);
            }
            ip += 2;
            break;

          case 24:
            peg$savedPos = stack[stack.length - 1 - bc[ip + 1]];
            ip += 2;
            break;

          case 25:
            peg$savedPos = peg$currPos;
            ip++;
            break;

          case 26:
            params = bc.slice(ip + 4, ip + 4 + bc[ip + 3]);
            for (i = 0; i < bc[ip + 3]; i++) {
              params[i] = stack[stack.length - 1 - params[i]];
            }

            stack.splice(
              stack.length - bc[ip + 2],
              bc[ip + 2],
              peg$consts[bc[ip + 1]].apply(null, params)
            );

            ip += 4 + bc[ip + 3];
            break;

          case 27:
            stack.push(peg$parseRule(bc[ip + 1]));
            ip += 2;
            break;

          case 28:
            peg$silentFails++;
            ip++;
            break;

          case 29:
            peg$silentFails--;
            ip++;
            break;

          default:
            throw new Error("Invalid opcode: " + bc[ip] + ".");
        }
      }

      if (ends.length > 0) {
        end = ends.pop();
        ip = ips.pop();
      } else {
        break;
      }
    }

    peg$resultsCache[key] = { nextPos: peg$currPos, result: stack[0] };

    return stack[0];
  }


    function makeText() {
      return {
        type: 'Text',
        text: text(),
        offset: location().start.offset
      };
    }


  peg$result = peg$parseRule(peg$startRuleIndex);

  if (peg$result !== peg$FAILED && peg$currPos === input.length) {
    return peg$result;
  } else {
    if (peg$result !== peg$FAILED && peg$currPos < input.length) {
      peg$fail(peg$endExpectation());
    }

    throw peg$buildStructuredError(
      peg$maxFailExpected,
      peg$maxFailPos < input.length ? input.charAt(peg$maxFailPos) : null,
      peg$maxFailPos < input.length
        ? peg$computeLocation(peg$maxFailPos, peg$maxFailPos + 1)
        : peg$computeLocation(peg$maxFailPos, peg$maxFailPos)
    );
  }
}

module.exports = {
  SyntaxError: peg$SyntaxError,
  parse:       peg$parse
};
